#:schema https://docs.jj-vcs.dev/latest/config-schema.json
[revset-aliases]
"closest_merge(to)" = "heads(::to & merges())"

[aliases]
stack = ["rebase", "--after", "trunk()", "--before", "closest_merge(@)", "--revision"]
